"""Generate COVERAGE.md and PROGRESS.md from the Master Study Plan topic list.

Run from the repository root:  python tools/build_index.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# (plan group, paper, topic, file, priority)
PLAN = [
    # ---------------- 1. Mathematics ----------------
    ("Discrete Mathematics", "CS", "Propositional logic", "01-discrete-mathematics/propositional-logic.md", "P0"),
    ("Discrete Mathematics", "CS", "First-order logic", "01-discrete-mathematics/first-order-logic.md", "P0"),
    ("Discrete Mathematics", "CS", "Sets", "01-discrete-mathematics/sets-relations-functions.md", "P1"),
    ("Discrete Mathematics", "CS", "Relations", "01-discrete-mathematics/sets-relations-functions.md", "P0"),
    ("Discrete Mathematics", "CS", "Functions", "01-discrete-mathematics/sets-relations-functions.md", "P0"),
    ("Discrete Mathematics", "CS", "Partial orders", "01-discrete-mathematics/posets-and-lattices.md", "P1"),
    ("Discrete Mathematics", "CS", "Lattices", "01-discrete-mathematics/posets-and-lattices.md", "P1"),
    ("Discrete Mathematics", "CS", "Monoids", "01-discrete-mathematics/algebraic-structures.md", "P1"),
    ("Discrete Mathematics", "CS", "Groups", "01-discrete-mathematics/algebraic-structures.md", "P0"),
    ("Discrete Mathematics", "CS", "Graphs: connectivity", "01-discrete-mathematics/graph-theory.md", "P0"),
    ("Discrete Mathematics", "CS", "Graphs: matching", "01-discrete-mathematics/graph-theory.md", "P1"),
    ("Discrete Mathematics", "CS", "Graphs: colouring", "01-discrete-mathematics/graph-theory.md", "P0"),
    ("Discrete Mathematics", "CS", "Combinatorics: counting", "01-discrete-mathematics/combinatorics.md", "P0"),
    ("Discrete Mathematics", "CS", "Recurrence relations", "01-discrete-mathematics/recurrences-and-generating-functions.md", "P0"),
    ("Discrete Mathematics", "CS", "Generating functions", "01-discrete-mathematics/recurrences-and-generating-functions.md", "P1"),
    ("Probability & Statistics", "CS+DA", "Counting: permutations and combinations", "02-probability-statistics/probability-basics.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Probability axioms", "02-probability-statistics/probability-basics.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Sample spaces and events", "02-probability-statistics/probability-basics.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Independent events", "02-probability-statistics/probability-basics.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Mutually exclusive events", "02-probability-statistics/probability-basics.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Marginal probability", "02-probability-statistics/probability-basics.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Conditional probability", "02-probability-statistics/probability-basics.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Joint probability", "02-probability-statistics/probability-basics.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Bayes theorem", "02-probability-statistics/probability-basics.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Conditional expectation", "02-probability-statistics/random-variables-and-moments.md", "P1"),
    ("Probability & Statistics", "CS+DA", "Conditional variance", "02-probability-statistics/random-variables-and-moments.md", "P1"),
    ("Probability & Statistics", "CS+DA", "Mean, median and mode", "02-probability-statistics/random-variables-and-moments.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Standard deviation", "02-probability-statistics/random-variables-and-moments.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Correlation", "02-probability-statistics/random-variables-and-moments.md", "P1"),
    ("Probability & Statistics", "CS+DA", "Covariance", "02-probability-statistics/random-variables-and-moments.md", "P1"),
    ("Probability & Statistics", "CS+DA", "Random variables", "02-probability-statistics/random-variables-and-moments.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Discrete random variables and PMFs", "02-probability-statistics/random-variables-and-moments.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Bernoulli distribution", "02-probability-statistics/discrete-distributions.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Binomial distribution", "02-probability-statistics/discrete-distributions.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Uniform distribution (discrete)", "02-probability-statistics/discrete-distributions.md", "P1"),
    ("Probability & Statistics", "CS+DA", "Continuous random variables and PDFs", "02-probability-statistics/random-variables-and-moments.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Uniform distribution (continuous)", "02-probability-statistics/continuous-distributions.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Exponential distribution", "02-probability-statistics/continuous-distributions.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Poisson distribution", "02-probability-statistics/discrete-distributions.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Normal distribution", "02-probability-statistics/continuous-distributions.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Standard normal distribution", "02-probability-statistics/continuous-distributions.md", "P0"),
    ("Probability & Statistics", "CS+DA", "t-distribution", "02-probability-statistics/continuous-distributions.md", "P1"),
    ("Probability & Statistics", "CS+DA", "Chi-squared distribution", "02-probability-statistics/continuous-distributions.md", "P1"),
    ("Probability & Statistics", "CS+DA", "Cumulative distribution function", "02-probability-statistics/random-variables-and-moments.md", "P0"),
    ("Probability & Statistics", "CS+DA", "Conditional PDF", "02-probability-statistics/random-variables-and-moments.md", "P1"),
    ("Probability & Statistics", "CS+DA", "Central limit theorem", "02-probability-statistics/statistical-inference.md", "P1"),
    ("Probability & Statistics", "CS+DA", "Confidence intervals", "02-probability-statistics/statistical-inference.md", "P1"),
    ("Probability & Statistics", "CS+DA", "z-test", "02-probability-statistics/statistical-inference.md", "P1"),
    ("Probability & Statistics", "CS+DA", "t-test", "02-probability-statistics/statistical-inference.md", "P1"),
    ("Probability & Statistics", "CS+DA", "Chi-squared test", "02-probability-statistics/statistical-inference.md", "P1"),
    ("Linear Algebra", "CS+DA", "Vectors and vector spaces", "03-linear-algebra/vector-spaces.md", "P1"),
    ("Linear Algebra", "CS+DA", "Subspaces", "03-linear-algebra/vector-spaces.md", "P1"),
    ("Linear Algebra", "CS+DA", "Linear dependence and independence", "03-linear-algebra/vector-spaces.md", "P0"),
    ("Linear Algebra", "CS+DA", "Matrices and matrix operations", "03-linear-algebra/matrices-and-determinants.md", "P0"),
    ("Linear Algebra", "CS+DA", "Projection matrices", "03-linear-algebra/orthogonality-projections-svd.md", "P1"),
    ("Linear Algebra", "CS+DA", "Orthogonal matrices", "03-linear-algebra/orthogonality-projections-svd.md", "P1"),
    ("Linear Algebra", "CS+DA", "Idempotent matrices", "03-linear-algebra/matrices-and-determinants.md", "P1"),
    ("Linear Algebra", "CS+DA", "Partition matrices and properties", "03-linear-algebra/matrices-and-determinants.md", "P2"),
    ("Linear Algebra", "CS+DA", "Quadratic forms", "03-linear-algebra/matrices-and-determinants.md", "P1"),
    ("Linear Algebra", "CS+DA", "Systems of linear equations and solutions", "03-linear-algebra/linear-systems-and-lu.md", "P0"),
    ("Linear Algebra", "CS+DA", "Gaussian elimination", "03-linear-algebra/linear-systems-and-lu.md", "P0"),
    ("Linear Algebra", "CS+DA", "Eigenvalues and eigenvectors", "03-linear-algebra/eigenvalues-and-eigenvectors.md", "P0"),
    ("Linear Algebra", "CS+DA", "Determinants", "03-linear-algebra/matrices-and-determinants.md", "P0"),
    ("Linear Algebra", "CS+DA", "Rank", "03-linear-algebra/vector-spaces.md", "P0"),
    ("Linear Algebra", "CS+DA", "Nullity", "03-linear-algebra/vector-spaces.md", "P0"),
    ("Linear Algebra", "CS+DA", "Projections", "03-linear-algebra/orthogonality-projections-svd.md", "P1"),
    ("Linear Algebra", "CS+DA", "LU decomposition", "03-linear-algebra/linear-systems-and-lu.md", "P1"),
    ("Linear Algebra", "CS+DA", "Singular value decomposition", "03-linear-algebra/orthogonality-projections-svd.md", "P1"),
    ("Calculus & Optimization", "CS+DA", "Functions of a single variable", "04-calculus-optimization/limits-continuity-differentiability.md", "P1"),
    ("Calculus & Optimization", "CS+DA", "Limits", "04-calculus-optimization/limits-continuity-differentiability.md", "P0"),
    ("Calculus & Optimization", "CS+DA", "Continuity", "04-calculus-optimization/limits-continuity-differentiability.md", "P0"),
    ("Calculus & Optimization", "CS+DA", "Differentiability", "04-calculus-optimization/limits-continuity-differentiability.md", "P0"),
    ("Calculus & Optimization", "CS+DA", "Taylor series", "04-calculus-optimization/mean-value-theorems-and-taylor.md", "P1"),
    ("Calculus & Optimization", "CS+DA", "Maxima and minima", "04-calculus-optimization/maxima-minima-optimization.md", "P0"),
    ("Calculus & Optimization", "CS+DA", "Mean value theorem", "04-calculus-optimization/mean-value-theorems-and-taylor.md", "P1"),
    ("Calculus & Optimization", "CS+DA", "Integration", "04-calculus-optimization/integration.md", "P1"),
    ("Calculus & Optimization", "CS+DA", "Single-variable optimization", "04-calculus-optimization/maxima-minima-optimization.md", "P0"),
    # ---------------- 2. Programming ----------------
    ("C Programming", "CS", "C syntax and semantics", "05-c-programming/c-basics-and-expressions.md", "P0"),
    ("C Programming", "CS", "Pointers", "05-c-programming/pointers-arrays-strings.md", "P0"),
    ("C Programming", "CS", "Arrays in C", "05-c-programming/pointers-arrays-strings.md", "P0"),
    ("C Programming", "CS", "Structures", "05-c-programming/functions-recursion-structures.md", "P1"),
    ("C Programming", "CS", "Functions", "05-c-programming/functions-recursion-structures.md", "P0"),
    ("C Programming", "CS", "Recursion in C", "05-c-programming/functions-recursion-structures.md", "P0"),
    ("C Programming", "CS", "Memory and pointer reasoning", "05-c-programming/pointers-arrays-strings.md", "P0"),
    ("C Programming", "CS", "Tracing C programs and expressions", "05-c-programming/c-basics-and-expressions.md", "P0"),
    ("Python Programming", "DA", "Python syntax", "06-python-programming/python-basics.md", "P0"),
    ("Python Programming", "DA", "Variables and expressions", "06-python-programming/python-basics.md", "P0"),
    ("Python Programming", "DA", "Functions", "06-python-programming/python-basics.md", "P0"),
    ("Python Programming", "DA", "Lists", "06-python-programming/python-collections.md", "P0"),
    ("Python Programming", "DA", "Tuples", "06-python-programming/python-collections.md", "P1"),
    ("Python Programming", "DA", "Dictionaries", "06-python-programming/python-collections.md", "P0"),
    ("Python Programming", "DA", "Sets", "06-python-programming/python-collections.md", "P1"),
    ("Python Programming", "DA", "Classes/basic OOP", "06-python-programming/python-oop-recursion-tracing.md", "P1"),
    ("Python Programming", "DA", "Iteration and loops", "06-python-programming/python-basics.md", "P0"),
    ("Python Programming", "DA", "Recursion", "06-python-programming/python-oop-recursion-tracing.md", "P0"),
    ("Python Programming", "DA", "Comprehensions", "06-python-programming/python-collections.md", "P1"),
    ("Python Programming", "DA", "Tracing Python programs", "06-python-programming/python-oop-recursion-tracing.md", "P0"),
    # ---------------- 3. Algorithms ----------------
    ("Data Structures", "CS+DA", "Arrays", "07-data-structures/arrays-stacks-queues.md", "P0"),
    ("Data Structures", "CS+DA", "Stacks", "07-data-structures/arrays-stacks-queues.md", "P0"),
    ("Data Structures", "CS+DA", "Queues", "07-data-structures/arrays-stacks-queues.md", "P0"),
    ("Data Structures", "CS+DA", "Linked lists", "07-data-structures/linked-lists.md", "P0"),
    ("Data Structures", "CS+DA", "Trees", "07-data-structures/trees-and-bst.md", "P0"),
    ("Data Structures", "CS+DA", "Binary search trees", "07-data-structures/trees-and-bst.md", "P0"),
    ("Data Structures", "CS+DA", "Binary heaps", "07-data-structures/heaps.md", "P0"),
    ("Data Structures", "CS+DA", "Graphs", "07-data-structures/graphs.md", "P1"),
    ("Data Structures", "CS+DA", "Data-structure operations and complexity", "07-data-structures/complexity-reference.md", "P0"),
    ("Algorithms", "CS+DA", "Asymptotic notation and growth rates", "08-algorithms/asymptotic-analysis.md", "P0"),
    ("Algorithms", "CS+DA", "Worst-case time complexity", "08-algorithms/asymptotic-analysis.md", "P0"),
    ("Algorithms", "CS+DA", "Worst-case space complexity", "08-algorithms/asymptotic-analysis.md", "P1"),
    ("Algorithms", "CS+DA", "Linear search", "08-algorithms/searching-and-sorting.md", "P1"),
    ("Algorithms", "CS+DA", "Binary search", "08-algorithms/searching-and-sorting.md", "P0"),
    ("Algorithms", "CS+DA", "Selection sort", "08-algorithms/searching-and-sorting.md", "P1"),
    ("Algorithms", "CS+DA", "Bubble sort", "08-algorithms/searching-and-sorting.md", "P1"),
    ("Algorithms", "CS+DA", "Insertion sort", "08-algorithms/searching-and-sorting.md", "P0"),
    ("Algorithms", "CS+DA", "Merge sort", "08-algorithms/searching-and-sorting.md", "P0"),
    ("Algorithms", "CS+DA", "Quicksort", "08-algorithms/searching-and-sorting.md", "P0"),
    ("Algorithms", "CS+DA", "Hashing", "08-algorithms/hashing.md", "P0"),
    ("Algorithms", "CS+DA", "Divide and conquer", "08-algorithms/divide-and-conquer.md", "P0"),
    ("Algorithms", "CS+DA", "Greedy algorithms", "08-algorithms/greedy-algorithms.md", "P0"),
    ("Algorithms", "CS+DA", "Dynamic programming", "08-algorithms/dynamic-programming.md", "P0"),
    ("Algorithms", "CS+DA", "Graph representations", "07-data-structures/graphs.md", "P1"),
    ("Algorithms", "CS+DA", "Graph traversal: BFS", "08-algorithms/graph-traversals.md", "P0"),
    ("Algorithms", "CS+DA", "Graph traversal: DFS", "08-algorithms/graph-traversals.md", "P0"),
    ("Algorithms", "CS+DA", "Minimum spanning trees", "08-algorithms/minimum-spanning-trees.md", "P0"),
    ("Algorithms", "CS+DA", "Shortest paths", "08-algorithms/shortest-paths.md", "P0"),
    # ---------------- 4. CS Core ----------------
    ("Digital Logic", "CS", "Boolean algebra", "09-digital-logic/boolean-algebra-and-minimization.md", "P0"),
    ("Digital Logic", "CS", "Boolean minimization: algebraic technique", "09-digital-logic/boolean-algebra-and-minimization.md", "P1"),
    ("Digital Logic", "CS", "Karnaugh maps", "09-digital-logic/boolean-algebra-and-minimization.md", "P0"),
    ("Digital Logic", "CS", "Tabular minimization method", "09-digital-logic/boolean-algebra-and-minimization.md", "P2"),
    ("Digital Logic", "CS", "Combinational circuit design", "09-digital-logic/combinational-circuits.md", "P0"),
    ("Digital Logic", "CS", "Sequential circuit design", "09-digital-logic/sequential-circuits.md", "P0"),
    ("Digital Logic", "CS", "Number representation", "09-digital-logic/number-representation-and-arithmetic.md", "P0"),
    ("Digital Logic", "CS", "Fixed-point arithmetic", "09-digital-logic/number-representation-and-arithmetic.md", "P1"),
    ("Digital Logic", "CS", "Floating-point arithmetic", "09-digital-logic/number-representation-and-arithmetic.md", "P0"),
    ("Computer Organization & Architecture", "CS", "Instruction sets", "10-computer-organization/instruction-sets-and-addressing.md", "P1"),
    ("Computer Organization & Architecture", "CS", "Addressing modes", "10-computer-organization/instruction-sets-and-addressing.md", "P0"),
    ("Computer Organization & Architecture", "CS", "ALU design", "10-computer-organization/alu-and-control-unit.md", "P2"),
    ("Computer Organization & Architecture", "CS", "Hardwired control unit", "10-computer-organization/alu-and-control-unit.md", "P1"),
    ("Computer Organization & Architecture", "CS", "Microprogrammed control unit", "10-computer-organization/alu-and-control-unit.md", "P1"),
    ("Computer Organization & Architecture", "CS", "Memory interfacing", "10-computer-organization/memory-hierarchy-and-cache.md", "P1"),
    ("Computer Organization & Architecture", "CS", "Memory hierarchy and performance", "10-computer-organization/memory-hierarchy-and-cache.md", "P0"),
    ("Computer Organization & Architecture", "CS", "Cache memory mapping", "10-computer-organization/memory-hierarchy-and-cache.md", "P0"),
    ("Computer Organization & Architecture", "CS", "I/O interface", "10-computer-organization/io-interrupts-dma.md", "P1"),
    ("Computer Organization & Architecture", "CS", "Interrupts", "10-computer-organization/io-interrupts-dma.md", "P1"),
    ("Computer Organization & Architecture", "CS", "DMA", "10-computer-organization/io-interrupts-dma.md", "P1"),
    ("Computer Organization & Architecture", "CS", "Instruction pipelining", "10-computer-organization/pipelining.md", "P0"),
    ("Computer Organization & Architecture", "CS", "Pipeline hazards", "10-computer-organization/pipelining.md", "P0"),
    ("Theory of Computation", "CS", "Regular expressions", "11-theory-of-computation/regular-languages-and-finite-automata.md", "P0"),
    ("Theory of Computation", "CS", "Finite automata", "11-theory-of-computation/regular-languages-and-finite-automata.md", "P0"),
    ("Theory of Computation", "CS", "Regular languages", "11-theory-of-computation/regular-languages-and-finite-automata.md", "P0"),
    ("Theory of Computation", "CS", "Context-free grammars", "11-theory-of-computation/context-free-languages-and-pda.md", "P0"),
    ("Theory of Computation", "CS", "Push-down automata", "11-theory-of-computation/context-free-languages-and-pda.md", "P1"),
    ("Theory of Computation", "CS", "Context-free languages", "11-theory-of-computation/context-free-languages-and-pda.md", "P0"),
    ("Theory of Computation", "CS", "Pumping lemma", "11-theory-of-computation/pumping-lemma.md", "P1"),
    ("Theory of Computation", "CS", "Turing machines", "11-theory-of-computation/turing-machines-and-undecidability.md", "P1"),
    ("Theory of Computation", "CS", "Undecidability", "11-theory-of-computation/turing-machines-and-undecidability.md", "P0"),
    ("Compiler Design", "CS", "Lexical analysis", "12-compiler-design/lexical-analysis.md", "P1"),
    ("Compiler Design", "CS", "Parsing", "12-compiler-design/parsing.md", "P0"),
    ("Compiler Design", "CS", "Syntax-directed translation", "12-compiler-design/syntax-directed-translation.md", "P0"),
    ("Compiler Design", "CS", "Runtime environments", "12-compiler-design/runtime-environments.md", "P1"),
    ("Compiler Design", "CS", "Intermediate code generation", "12-compiler-design/intermediate-code-generation.md", "P1"),
    ("Compiler Design", "CS", "Local optimization", "12-compiler-design/optimization-and-dataflow.md", "P1"),
    ("Compiler Design", "CS", "Data-flow analysis", "12-compiler-design/optimization-and-dataflow.md", "P1"),
    ("Compiler Design", "CS", "Constant propagation", "12-compiler-design/optimization-and-dataflow.md", "P1"),
    ("Compiler Design", "CS", "Liveness analysis", "12-compiler-design/optimization-and-dataflow.md", "P0"),
    ("Compiler Design", "CS", "Common subexpression elimination", "12-compiler-design/optimization-and-dataflow.md", "P1"),
    # ---------------- 5. Systems ----------------
    ("Operating Systems", "CS", "System calls", "13-operating-systems/processes-threads-syscalls.md", "P1"),
    ("Operating Systems", "CS", "Processes", "13-operating-systems/processes-threads-syscalls.md", "P0"),
    ("Operating Systems", "CS", "Threads", "13-operating-systems/processes-threads-syscalls.md", "P1"),
    ("Operating Systems", "CS", "Inter-process communication", "13-operating-systems/processes-threads-syscalls.md", "P2"),
    ("Operating Systems", "CS", "Concurrency", "13-operating-systems/synchronization.md", "P0"),
    ("Operating Systems", "CS", "Synchronization", "13-operating-systems/synchronization.md", "P0"),
    ("Operating Systems", "CS", "Deadlocks", "13-operating-systems/deadlocks.md", "P0"),
    ("Operating Systems", "CS", "CPU scheduling", "13-operating-systems/cpu-scheduling.md", "P0"),
    ("Operating Systems", "CS", "I/O scheduling", "13-operating-systems/file-systems-and-disk-scheduling.md", "P1"),
    ("Operating Systems", "CS", "Memory management", "13-operating-systems/memory-management.md", "P0"),
    ("Operating Systems", "CS", "Virtual memory", "13-operating-systems/virtual-memory.md", "P0"),
    ("Operating Systems", "CS", "File systems", "13-operating-systems/file-systems-and-disk-scheduling.md", "P1"),
    ("DBMS & Data Warehousing", "CS+DA", "ER model", "14-databases/er-model.md", "P1"),
    ("DBMS & Data Warehousing", "CS+DA", "Relational model", "14-databases/relational-model-algebra-calculus.md", "P0"),
    ("DBMS & Data Warehousing", "CS+DA", "Relational algebra", "14-databases/relational-model-algebra-calculus.md", "P0"),
    ("DBMS & Data Warehousing", "CS+DA", "Tuple calculus", "14-databases/relational-model-algebra-calculus.md", "P1"),
    ("DBMS & Data Warehousing", "CS+DA", "SQL", "14-databases/sql.md", "P0"),
    ("DBMS & Data Warehousing", "CS+DA", "Integrity constraints", "14-databases/constraints-and-normalization.md", "P1"),
    ("DBMS & Data Warehousing", "CS+DA", "Normal forms", "14-databases/constraints-and-normalization.md", "P0"),
    ("DBMS & Data Warehousing", "CS+DA", "File organization", "14-databases/file-organization-and-indexing.md", "P1"),
    ("DBMS & Data Warehousing", "CS+DA", "Indexing", "14-databases/file-organization-and-indexing.md", "P0"),
    ("DBMS & Data Warehousing", "CS+DA", "B trees", "14-databases/file-organization-and-indexing.md", "P0"),
    ("DBMS & Data Warehousing", "CS+DA", "B+ trees", "14-databases/file-organization-and-indexing.md", "P0"),
    ("DBMS & Data Warehousing", "CS+DA", "Transactions", "14-databases/transactions-and-concurrency.md", "P0"),
    ("DBMS & Data Warehousing", "CS+DA", "Concurrency control", "14-databases/transactions-and-concurrency.md", "P0"),
    ("DBMS & Data Warehousing", "CS+DA", "Data types", "14-databases/data-warehousing-and-preprocessing.md", "P1"),
    ("DBMS & Data Warehousing", "CS+DA", "Data transformation: normalization", "14-databases/data-warehousing-and-preprocessing.md", "P1"),
    ("DBMS & Data Warehousing", "CS+DA", "Discretization", "14-databases/data-warehousing-and-preprocessing.md", "P1"),
    ("DBMS & Data Warehousing", "CS+DA", "Sampling", "14-databases/data-warehousing-and-preprocessing.md", "P1"),
    ("DBMS & Data Warehousing", "CS+DA", "Compression", "14-databases/data-warehousing-and-preprocessing.md", "P2"),
    ("DBMS & Data Warehousing", "CS+DA", "Data warehouse schemas for multidimensional models", "14-databases/data-warehousing-and-preprocessing.md", "P1"),
    ("DBMS & Data Warehousing", "CS+DA", "Concept hierarchies", "14-databases/data-warehousing-and-preprocessing.md", "P1"),
    ("DBMS & Data Warehousing", "CS+DA", "Measures: categorization and computation", "14-databases/data-warehousing-and-preprocessing.md", "P1"),
    ("Computer Networks", "CS", "Principles of layering", "15-computer-networks/layering-switching-performance.md", "P1"),
    ("Computer Networks", "CS", "Circuit switching", "15-computer-networks/layering-switching-performance.md", "P1"),
    ("Computer Networks", "CS", "Packet switching", "15-computer-networks/layering-switching-performance.md", "P0"),
    ("Computer Networks", "CS", "Virtual circuit switching", "15-computer-networks/layering-switching-performance.md", "P2"),
    ("Computer Networks", "CS", "Network performance metrics", "15-computer-networks/layering-switching-performance.md", "P0"),
    ("Computer Networks", "CS", "Data-link layer", "15-computer-networks/data-link-layer.md", "P0"),
    ("Computer Networks", "CS", "Error detection", "15-computer-networks/data-link-layer.md", "P0"),
    ("Computer Networks", "CS", "Medium Access Control", "15-computer-networks/data-link-layer.md", "P0"),
    ("Computer Networks", "CS", "Ethernet", "15-computer-networks/data-link-layer.md", "P1"),
    ("Computer Networks", "CS", "Distance-vector routing", "15-computer-networks/routing.md", "P0"),
    ("Computer Networks", "CS", "Link-state routing", "15-computer-networks/routing.md", "P1"),
    ("Computer Networks", "CS", "IPv4", "15-computer-networks/ipv4-addressing.md", "P0"),
    ("Computer Networks", "CS", "IPv4 fragmentation", "15-computer-networks/ipv4-addressing.md", "P0"),
    ("Computer Networks", "CS", "CIDR notation", "15-computer-networks/ipv4-addressing.md", "P0"),
    ("Computer Networks", "CS", "Network Address Translation", "15-computer-networks/ipv4-addressing.md", "P1"),
    ("Computer Networks", "CS", "TCP flow control", "15-computer-networks/transport-layer-tcp.md", "P0"),
    ("Computer Networks", "CS", "TCP congestion control", "15-computer-networks/transport-layer-tcp.md", "P0"),
    ("Computer Networks", "CS", "Socket API", "15-computer-networks/transport-layer-tcp.md", "P1"),
    ("Computer Networks", "CS", "DNS", "15-computer-networks/application-layer.md", "P1"),
    ("Computer Networks", "CS", "HTTP", "15-computer-networks/application-layer.md", "P1"),
    # ---------------- 6. Data Science & AI ----------------
    ("Machine Learning", "DA", "Regression vs classification problems", "16-machine-learning/ml-foundations.md", "P0"),
    ("Machine Learning", "DA", "Simple linear regression", "16-machine-learning/linear-and-logistic-regression.md", "P0"),
    ("Machine Learning", "DA", "Multiple linear regression", "16-machine-learning/linear-and-logistic-regression.md", "P0"),
    ("Machine Learning", "DA", "Ridge regression", "16-machine-learning/linear-and-logistic-regression.md", "P1"),
    ("Machine Learning", "DA", "Logistic regression", "16-machine-learning/linear-and-logistic-regression.md", "P0"),
    ("Machine Learning", "DA", "k-nearest neighbours", "16-machine-learning/classification-methods.md", "P0"),
    ("Machine Learning", "DA", "Naive Bayes classifier", "16-machine-learning/classification-methods.md", "P0"),
    ("Machine Learning", "DA", "Linear discriminant analysis", "16-machine-learning/classification-methods.md", "P1"),
    ("Machine Learning", "DA", "Support vector machines", "16-machine-learning/classification-methods.md", "P0"),
    ("Machine Learning", "DA", "Decision trees", "16-machine-learning/classification-methods.md", "P0"),
    ("Machine Learning", "DA", "Bias-variance trade-off", "16-machine-learning/ml-foundations.md", "P0"),
    ("Machine Learning", "DA", "Leave-one-out cross-validation", "16-machine-learning/ml-foundations.md", "P1"),
    ("Machine Learning", "DA", "k-fold cross-validation", "16-machine-learning/ml-foundations.md", "P1"),
    ("Machine Learning", "DA", "Multi-layer perceptron", "16-machine-learning/neural-networks.md", "P0"),
    ("Machine Learning", "DA", "Feed-forward neural networks", "16-machine-learning/neural-networks.md", "P0"),
    ("Machine Learning", "DA", "Clustering", "16-machine-learning/clustering.md", "P0"),
    ("Machine Learning", "DA", "k-means", "16-machine-learning/clustering.md", "P0"),
    ("Machine Learning", "DA", "k-medoids", "16-machine-learning/clustering.md", "P1"),
    ("Machine Learning", "DA", "Hierarchical clustering: top-down", "16-machine-learning/clustering.md", "P1"),
    ("Machine Learning", "DA", "Hierarchical clustering: bottom-up", "16-machine-learning/clustering.md", "P0"),
    ("Machine Learning", "DA", "Single-linkage clustering", "16-machine-learning/clustering.md", "P0"),
    ("Machine Learning", "DA", "Multiple-linkage clustering", "16-machine-learning/clustering.md", "P1"),
    ("Machine Learning", "DA", "Dimensionality reduction", "16-machine-learning/dimensionality-reduction-pca.md", "P1"),
    ("Machine Learning", "DA", "Principal component analysis", "16-machine-learning/dimensionality-reduction-pca.md", "P0"),
    ("Artificial Intelligence", "DA", "Uninformed search", "17-artificial-intelligence/search.md", "P0"),
    ("Artificial Intelligence", "DA", "Informed search", "17-artificial-intelligence/search.md", "P0"),
    ("Artificial Intelligence", "DA", "Adversarial search", "17-artificial-intelligence/search.md", "P0"),
    ("Artificial Intelligence", "DA", "Propositional logic", "17-artificial-intelligence/logic-and-inference.md", "P0"),
    ("Artificial Intelligence", "DA", "Predicate logic", "17-artificial-intelligence/logic-and-inference.md", "P1"),
    ("Artificial Intelligence", "DA", "Conditional independence", "17-artificial-intelligence/probabilistic-reasoning.md", "P0"),
    ("Artificial Intelligence", "DA", "Representation of conditional independence", "17-artificial-intelligence/probabilistic-reasoning.md", "P0"),
    ("Artificial Intelligence", "DA", "Exact inference via variable elimination", "17-artificial-intelligence/probabilistic-reasoning.md", "P0"),
    ("Artificial Intelligence", "DA", "Approximate inference via sampling", "17-artificial-intelligence/probabilistic-reasoning.md", "P1"),
]

PARTS = {
    "Discrete Mathematics": "1. Mathematics", "Probability & Statistics": "1. Mathematics",
    "Linear Algebra": "1. Mathematics", "Calculus & Optimization": "1. Mathematics",
    "C Programming": "2. Programming", "Python Programming": "2. Programming",
    "Data Structures": "3. Algorithms", "Algorithms": "3. Algorithms",
    "Digital Logic": "4. CS Core", "Computer Organization & Architecture": "4. CS Core",
    "Theory of Computation": "4. CS Core", "Compiler Design": "4. CS Core",
    "Operating Systems": "5. Systems", "DBMS & Data Warehousing": "5. Systems",
    "Computer Networks": "5. Systems", "Machine Learning": "6. Data Science & AI",
    "Artificial Intelligence": "6. Data Science & AI",
}

# Topics added beyond the plan: (area, paper, topic, file, why)
ADDED = [
    ("General Aptitude", "CS+DA", "Verbal aptitude", "00-general-aptitude/verbal-aptitude.md", "15-mark GA section is in every paper; absent from the plan"),
    ("General Aptitude", "CS+DA", "Quantitative aptitude", "00-general-aptitude/quantitative-aptitude.md", "same"),
    ("General Aptitude", "CS+DA", "Analytical aptitude", "00-general-aptitude/analytical-aptitude.md", "same"),
    ("General Aptitude", "CS+DA", "Spatial aptitude", "00-general-aptitude/spatial-aptitude.md", "same"),
    ("Discrete Mathematics", "CS", "Pigeonhole, inclusion-exclusion, Catalan numbers, derangements", "01-discrete-mathematics/combinatorics.md", "standard tools behind 'Combinatorics: counting'"),
    ("Discrete Mathematics", "CS", "Euler/Hamiltonian graphs, planarity, trees", "01-discrete-mathematics/graph-theory.md", "routinely asked under 'Graphs'"),
    ("Probability & Statistics", "CS+DA", "Geometric distribution, memorylessness, Poisson process", "02-probability-statistics/discrete-distributions.md", "needed to work exponential/Poisson problems"),
    ("Linear Algebra", "CS+DA", "Cayley-Hamilton, diagonalisation, positive definiteness", "03-linear-algebra/eigenvalues-and-eigenvectors.md", "standard eigenvalue tools"),
    ("C Programming", "CS", "Static vs dynamic scoping, parameter-passing modes", "05-c-programming/functions-recursion-structures.md", "frequent PYQ theme under 'Functions'"),
    ("Data Structures", "CS+DA", "AVL trees, infix/postfix conversion, circular queues", "07-data-structures/trees-and-bst.md", "frequent PYQ themes under 'Trees' / 'Stacks'"),
    ("Algorithms", "CS+DA", "Master theorem and recursion trees", "08-algorithms/asymptotic-analysis.md", "needed for 'Worst-case time complexity'"),
    ("Algorithms", "CS+DA", "Heap sort, counting/radix sort, sorting lower bound", "08-algorithms/searching-and-sorting.md", "part of 'sorting' in the official syllabus"),
    ("Algorithms", "CS+DA", "Topological sort, SCCs, Bellman-Ford, Floyd-Warshall", "08-algorithms/graph-traversals.md", "applications of traversals / shortest paths"),
    ("Theory of Computation", "CS", "DFA minimisation, closure & decidability tables, Rice's theorem", "11-theory-of-computation/turing-machines-and-undecidability.md", "how 'Undecidability' and 'Regular languages' are asked"),
    ("Compiler Design", "CS", "FIRST/FOLLOW, LL(1), LR(0)/SLR/LALR/CLR tables", "12-compiler-design/parsing.md", "the substance of 'Parsing'"),
    ("Compiler Design", "CS", "Basic blocks, CFGs, register allocation by colouring", "12-compiler-design/intermediate-code-generation.md", "prerequisite for data-flow analysis"),
    ("Operating Systems", "CS", "fork() counting, page replacement, Banker's algorithm, TLB/EMAT", "13-operating-systems/virtual-memory.md", "the substance of 'Processes', 'Virtual memory', 'Deadlocks'"),
    ("DBMS", "CS+DA", "Serializability, recoverability, 2PL, timestamp ordering", "14-databases/transactions-and-concurrency.md", "the substance of 'Concurrency control'"),
    ("DBMS", "CS+DA", "FD closure, candidate keys, lossless join, dependency preservation", "14-databases/constraints-and-normalization.md", "the substance of 'Normal forms'"),
    ("DBMS", "CS+DA", "OLAP operations, data cube, cuboid counting", "14-databases/data-warehousing-and-preprocessing.md", "context for warehouse schemas"),
    ("Computer Networks", "CS", "Sliding-window protocols (stop-and-wait, GBN, SR)", "15-computer-networks/data-link-layer.md", "underpin TCP flow control; classic numericals"),
    ("Computer Networks", "CS", "TCP handshake, sequence numbers, UDP contrast", "15-computer-networks/transport-layer-tcp.md", "needed to reason about TCP flow/congestion control"),
    ("Machine Learning", "DA", "Evaluation metrics, loss functions, gradient descent, backpropagation", "16-machine-learning/ml-foundations.md", "needed to answer model questions"),
    ("Artificial Intelligence", "DA", "Bayesian networks, d-separation, resolution, unification", "17-artificial-intelligence/probabilistic-reasoning.md", "the substance of 'representation of conditional independence' and logic"),
]


def link(path: str) -> str:
    title = path.split("/")[-1].removesuffix(".md")
    return f"[{title}]({path})"


def coverage() -> str:
    out = [
        "# Coverage audit",
        "",
        "Every topic in the *GATE 2027 CS + DA Master Study Plan*, mapped to the chapter that teaches it. Both official GATE 2027 syllabi (CS and DA, IIT Madras) were checked against the plan.",
        "",
        "## Audit result",
        "",
        "- **Missing from the plan:** General Aptitude (15 marks in both papers). It is now [section 00](00-general-aptitude/README.md).",
        "- **Everything else in the official CS and DA syllabi is in the plan.** The plan's topic list follows the 2027 syllabus wording closely.",
        "- **Extra items in the plan were kept as instructed.** Some are tagged CS+DA but appear in only one official syllabus. Data types, data-transformation normalization, discretization, sampling, compression, warehouse schemas, concept hierarchies and measures are **DA-only**. Mean value theorem and integration are **CS-only**. Projection/orthogonal/idempotent/partition matrices, quadratic forms, Gaussian elimination, rank, nullity, projections and SVD are **DA-only** (CS lists only matrices, determinants, systems of equations, eigen-things and LU). Most of probability (t / chi-squared distributions, CLT, confidence intervals, tests, covariance/correlation, conditional expectation/variance, conditional PDF) is **DA-only**. CS lists random variables, the uniform/normal/exponential/Poisson/binomial distributions, mean/median/mode/SD, conditional probability and Bayes. CS students can treat those chapters as P2.",
        "- **2027 changes to note:** the CS networks syllabus is narrower than in earlier years. It names layering; switching and performance metrics; error detection, MAC and Ethernet; DV/LS routing; IPv4 fragmentation, CIDR and NAT; TCP flow/congestion control and sockets; DNS and HTTP. ARP/DHCP/ICMP, UDP, SMTP/FTP and framing/bridging are no longer named. Older PYQs on those topics are lower priority.",
        "",
        "## Plan topics → chapters",
        "",
        "Plan group | Paper | Topic | Taught in | Priority",
        "--- | --- | --- | --- | ---",
    ]
    for group, paper, topic, path, prio in PLAN:
        out.append(f"{group} | {paper} | {topic} | {link(path)} | {prio}")
    out += [
        "",
        "## Topics added beyond the plan",
        "",
        "These are not separate items in the plan. They are either missing (General Aptitude) or are the standard machinery GATE uses to test a listed topic, so each is taught inside the chapter it supports.",
        "",
        "Area | Paper | Topic | Taught in | Why it is included",
        "--- | --- | --- | --- | ---",
    ]
    for area, paper, topic, path, why in ADDED:
        out.append(f"{area} | {paper} | {topic} | {link(path)} | {why}")
    out += ["", "[Roadmap](ROADMAP.md) · [Progress](PROGRESS.md) · [Structure](STRUCTURE.md)", ""]
    return "\n".join(out)


def progress() -> str:
    out = [
        "# Progress",
        "",
        "Same order as the Master Study Plan. Tick a topic only when you have (1) read the chapter, (2) rewritten its Quick glance from memory, (3) solved its Practice questions, and (4) solved that topic's PYQs. Leave a mark in the `R1 R2 R3` columns each time you revise it.",
        "",
        "**P0** = asked almost every year · **P1** = asked regularly · **P2** = occasional.",
        "",
        "## 0. General Aptitude (added)",
        "",
        "- [ ] P0 — Verbal aptitude ([study](00-general-aptitude/verbal-aptitude.md))",
        "- [ ] P0 — Quantitative aptitude ([study](00-general-aptitude/quantitative-aptitude.md))",
        "- [ ] P0 — Analytical aptitude ([study](00-general-aptitude/analytical-aptitude.md))",
        "- [ ] P1 — Spatial aptitude ([study](00-general-aptitude/spatial-aptitude.md))",
    ]
    part = group = None
    for g, paper, topic, path, prio in PLAN:
        if PARTS[g] != part:
            part = PARTS[g]
            out += ["", f"## {part}"]
            group = None
        if g != group:
            group = g
            out += ["", f"### {g} ({paper})", ""]
        out.append(f"- [ ] {prio} — {topic} ([study]({path})) · R1 ☐ R2 ☐ R3 ☐")
    out += ["", "[Roadmap](ROADMAP.md) · [Coverage](COVERAGE.md) · [Cheat sheets](CHEATSHEETS.md)", ""]
    return "\n".join(out)


if __name__ == "__main__":
    (ROOT / "COVERAGE.md").write_text(coverage(), encoding="utf-8")
    (ROOT / "PROGRESS.md").write_text(progress(), encoding="utf-8")
    print(f"{len(PLAN)} plan topics, {len(ADDED)} added topics")
